name: iOS starter workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

    steps:
    - name: Set up certificate and provisioning profile
      run: |
        CERTIFICATE_PATH=$RUNNER_TEMP/Certificate.p12
        PP_PATH=$RUNNER_TEMP/DemoTest.mobileprovision

        echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
        echo "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > $PP_PATH

        security create-keychain -p "" temporary.keychain
        security import $CERTIFICATE_PATH -k temporary.keychain -P "$P12_PASSWORD" -A -t cert -f pkcs12
        security list-keychain -d user -s temporary.keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "" temporary.keychain
        security set-keychain-settings -lut 21600 temporary.keychain

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      env:
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
