name: iOS starter workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install the Apple certificate and provisioning profile
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          # Copy the certificate and provisioning profile to the correct locations
          cp Certificates.p12 $RUNNER_TEMP/build_certificate.p12
          cp DemoTest.mobileprovision $RUNNER_TEMP/build_pp.mobileprovision

          # Import the certificate to the user keychain
          security import $RUNNER_TEMP/build_certificate.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k ~/Library/Keychains/login.keychain-db
          security list-keychain -d user -s ~/Library/Keychains/login.keychain-db

          # Apply the provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $RUNNER_TEMP/build_pp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
      
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      
      - name: Copy Podfile
        run: cp -r SignIn/Podfile .
        
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo list
          pod setup
      
      - name: Install dependencies
        run: pod install --project-directory=SignIn/
      
      - name: Check current directory
        run: |
          pwd
          ls -al 
     
      - name: Navigate to SignIn folder
        run: |
          cd SignIn/
          ls

      - name: build archive
        run: |
          xcodebuild -scheme "SignIn" \
          -archivePath $RUNNER_TEMP/signin.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive
