name: iOS starter workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Set up certificate and provisioning profile
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/Certificate.p12
          PP_PATH=$RUNNER_TEMP/DemoTest.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
          echo "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > $PP_PATH

          # Generate a random keychain password
          KEYCHAIN_PASSWORD=$(openssl rand -base64 12 | tr -d /=+)

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

