name: iOS starter workflow
on: 
  push:   
    branches:
      - main 
  pull_request:   
    branches: 
      - main     
        
jobs: 
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Copy Podfile
        run: cp -r SignIn/Podfile .

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v '1.11.2'
          pod repo list
          pod setup

      - name: Install dependencies
        run: pod install --project-directory=SignIn/
